
ENVIRONMENT:
  local_url: "http://localhost:7071/api/ocean_pta_v1"
  dev_url: "https://ocean-pta-app-lana-dev-01.azurewebsites.net/api/ocean_pta_v1"
  model_store_path: "/Users/Andrewlanders/projects/ocean_pta/models/v2/model_store"

IS_LOCAL_RUN: True
LOGGING_LEVEL: DEBUG

RUN_PARAMS:
  run_continuous: True
  randomize_routes: True
  num_of_batches: 3
  concurrent_payloads: 5
  items_per_payload: 10
